# Generated by Django 3.2.8 on 2022-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
